name: WhatCrate

description: WhatCrates is a crate plugin for Pocketmine-MP Servers.
version: 1.2.0-pre
author: SchdowNVIDIA
api: 3.0.0
main: SchdowNVIDIA\WhatCrates\Main

permissions:
  whatcrates:
    default: op
    description: WhatCrates command permission
